name       : perl-role-tiny
version    : 2.000005
release    : 1
source     :
    - http://search.cpan.org/CPAN/authors/id/H/HA/HAARG/Role-Tiny-2.000005.tar.gz : 593a29b621e029bf0218d0154d5dfdf6ec502afc49adeeadae6afd0c70063115
license    : Artistic-2.0
component  : programming.perl
summary    : Roles. Like a nouvelle cuisine portion size slice of Moose.
description: |
    Roles. Like a nouvelle cuisine portion size slice of Moose.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
