name       : perl-role-tiny
version    : 2.000006
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.000006.tar.gz : cc73418c904a0286ecd8915eac11f5be2a8d1e17ea9cb54c9116b0340cd3e382
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Roles. Like a nouvelle cuisine portion size slice of Moose.
description: |
    Roles. Like a nouvelle cuisine portion size slice of Moose.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
