name       : perl-role-tiny
version    : '2.002004'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.002004.tar.gz : d7bdee9e138a4f83aa52d0a981625644bda87ff16642dfa845dcb44d9a242b45
homepage   : https://metacpan.org/pod/Role::Tiny
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Role::Tiny - A nouvelle cuisine portion size slice of Moose
description: |
    This is a minimalist role composition tool. Like a nouvelle cuisine portion size slice of Moose.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
