name       : perl-role-tiny
version    : '2.001004'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/H/HA/HAARG/Role-Tiny-2.001004.tar.gz : 92ba5712850a74102c93c942eb6e7f62f7a4f8f483734ed289d08b324c281687
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : Roles. Like a nouvelle cuisine portion size slice of Moose.
description: |
    Roles. Like a nouvelle cuisine portion size slice of Moose.
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %perl_build test
